{"discounts":[
    {"storeName":"1-800 Flowers", "id":"158", "url":"http://www.cardbear.com/gift-card-discount/158/1-800+Flowers", "highestDiscount":"32.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"7 For All Mankind", "id":"145", "url":"http://www.cardbear.com/gift-card-discount/145/7+For+All+Mankind", "highestDiscount":"12.30", "highestDiscountReseller":"cardcash"},
    {"storeName":"76 Gas", "id":"496", "url":"http://www.cardbear.com/gift-card-discount/496/76+Gas", "highestDiscount":"1.50", "highestDiscountReseller":"raise"},
    {"storeName":"A.C. Moore", "id":"146", "url":"http://www.cardbear.com/gift-card-discount/146/A.C.+Moore", "highestDiscount":"20.95", "highestDiscountReseller":"cardcash"},
    {"storeName":"Aaron Brothers", "id":"147", "url":"http://www.cardbear.com/gift-card-discount/147/Aaron+Brothers", "highestDiscount":"0.20", "highestDiscountReseller":"raise"},
    {"storeName":"Abercrombie & Fitch", "id":"3", "url":"http://www.cardbear.com/gift-card-discount/3/Abercrombie+%26+Fitch", "highestDiscount":"8.00", "highestDiscountReseller":"raise"},
    {"storeName":"Abercrombie Kids", "id":"249", "url":"http://www.cardbear.com/gift-card-discount/249/Abercrombie+Kids", "highestDiscount":"5.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Academy Sports", "id":"148", "url":"http://www.cardbear.com/gift-card-discount/148/Academy+Sports", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Ace Hardware", "id":"323", "url":"http://www.cardbear.com/gift-card-discount/323/Ace+Hardware", "highestDiscount":"2.00", "highestDiscountReseller":"raise"},
    {"storeName":"Adidas", "id":"43", "url":"http://www.cardbear.com/gift-card-discount/43/Adidas", "highestDiscount":"5.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Advance Auto Parts", "id":"44", "url":"http://www.cardbear.com/gift-card-discount/44/Advance+Auto+Parts", "highestDiscount":"15.17", "highestDiscountReseller":"cardcash"},
    {"storeName":"Aerie", "id":"407", "url":"http://www.cardbear.com/gift-card-discount/407/Aerie", "highestDiscount":"10.00", "highestDiscountReseller":"raise"},
    {"storeName":"Aeropostale", "id":"68", "url":"http://www.cardbear.com/gift-card-discount/68/Aeropostale", "highestDiscount":"11.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Aerosoles", "id":"132", "url":"http://www.cardbear.com/gift-card-discount/132/Aerosoles", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Albertsons", "id":"154", "url":"http://www.cardbear.com/gift-card-discount/154/Albertsons", "highestDiscount":"1.70", "highestDiscountReseller":"raise"},
    {"storeName":"Aldo", "id":"131", "url":"http://www.cardbear.com/gift-card-discount/131/Aldo", "highestDiscount":"22.00", "highestDiscountReseller":"raise"},
    {"storeName":"Allen Edmonds", "id":"373", "url":"http://www.cardbear.com/gift-card-discount/373/Allen+Edmonds", "highestDiscount":"10.70", "highestDiscountReseller":"cardcash"},
    {"storeName":"Amazon", "id":"111", "url":"http://www.cardbear.com/gift-card-discount/111/Amazon", "highestDiscount":"0.50", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"AMC", "id":"110", "url":"http://www.cardbear.com/gift-card-discount/110/AMC", "highestDiscount":"18.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"American Airlines", "id":"153", "url":"http://www.cardbear.com/gift-card-discount/153/American+Airlines", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"American Apparel", "id":"155", "url":"http://www.cardbear.com/gift-card-discount/155/American+Apparel", "highestDiscount":"27.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"American Eagle Outfitters", "id":"36", "url":"http://www.cardbear.com/gift-card-discount/36/American+Eagle+Outfitters", "highestDiscount":"14.10", "highestDiscountReseller":"saveya"},
    {"storeName":"American Express", "id":"432", "url":"http://www.cardbear.com/gift-card-discount/432/American+Express", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"American Girl", "id":"37", "url":"http://www.cardbear.com/gift-card-discount/37/American+Girl", "highestDiscount":"8.40", "highestDiscountReseller":"raise"},
    {"storeName":"AMF Bowling", "id":"433", "url":"http://www.cardbear.com/gift-card-discount/433/AMF+Bowling", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Ann Taylor", "id":"16", "url":"http://www.cardbear.com/gift-card-discount/16/Ann+Taylor", "highestDiscount":"27.09", "highestDiscountReseller":"cardcash"},
    {"storeName":"Anna's Linen", "id":"434", "url":"http://www.cardbear.com/gift-card-discount/434/Anna%27s+Linen", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Anthropologie", "id":"130", "url":"http://www.cardbear.com/gift-card-discount/130/Anthropologie", "highestDiscount":"18.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Any Mountain", "id":"262", "url":"http://www.cardbear.com/gift-card-discount/262/Any+Mountain", "highestDiscount":"22.00", "highestDiscountReseller":"raise"},
    {"storeName":"Apple iTunes", "id":"96", "url":"http://www.cardbear.com/gift-card-discount/96/Apple+iTunes", "highestDiscount":"8.80", "highestDiscountReseller":"saveya"},
    {"storeName":"Apple Store", "id":"5", "url":"http://www.cardbear.com/gift-card-discount/5/Apple+Store", "highestDiscount":"0.70", "highestDiscountReseller":"raise"},
    {"storeName":"Applebee's", "id":"108", "url":"http://www.cardbear.com/gift-card-discount/108/Applebee%27s", "highestDiscount":"26.10", "highestDiscountReseller":"cardcash"},
    {"storeName":"Arby's", "id":"351", "url":"http://www.cardbear.com/gift-card-discount/351/Arby%27s", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Arco", "id":"443", "url":"http://www.cardbear.com/gift-card-discount/443/Arco", "highestDiscount":"0.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Armani Exchange", "id":"149", "url":"http://www.cardbear.com/gift-card-discount/149/Armani+Exchange", "highestDiscount":"8.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Art of Shaving", "id":"321", "url":"http://www.cardbear.com/gift-card-discount/321/Art+of+Shaving", "highestDiscount":"19.40", "highestDiscountReseller":"raise"},
    {"storeName":"Ashley Stewart", "id":"159", "url":"http://www.cardbear.com/gift-card-discount/159/Ashley+Stewart", "highestDiscount":"26.00", "highestDiscountReseller":"raise"},
    {"storeName":"Athleta", "id":"6", "url":"http://www.cardbear.com/gift-card-discount/6/Athleta", "highestDiscount":"11.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"AutoZone", "id":"117", "url":"http://www.cardbear.com/gift-card-discount/117/AutoZone", "highestDiscount":"23.70", "highestDiscountReseller":"cardcash"},
    {"storeName":"Avenue", "id":"160", "url":"http://www.cardbear.com/gift-card-discount/160/Avenue", "highestDiscount":"30.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Avis", "id":"34", "url":"http://www.cardbear.com/gift-card-discount/34/Avis", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Babies R Us", "id":"150", "url":"http://www.cardbear.com/gift-card-discount/150/Babies+R+Us", "highestDiscount":"7.48", "highestDiscountReseller":"saveya"},
    {"storeName":"Baby Gap", "id":"151", "url":"http://www.cardbear.com/gift-card-discount/151/Baby+Gap", "highestDiscount":"11.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Bahama Breeze", "id":"339", "url":"http://www.cardbear.com/gift-card-discount/339/Bahama+Breeze", "highestDiscount":"16.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Baja Fresh", "id":"328", "url":"http://www.cardbear.com/gift-card-discount/328/Baja+Fresh", "highestDiscount":"10.00", "highestDiscountReseller":"raise"},
    {"storeName":"Banana Republic", "id":"144", "url":"http://www.cardbear.com/gift-card-discount/144/Banana+Republic", "highestDiscount":"11.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Bar Louie", "id":"240", "url":"http://www.cardbear.com/gift-card-discount/240/Bar+Louie", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Bare Minerals", "id":"161", "url":"http://www.cardbear.com/gift-card-discount/161/Bare+Minerals", "highestDiscount":"19.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"Barnes & Noble", "id":"69", "url":"http://www.cardbear.com/gift-card-discount/69/Barnes+%26+Noble", "highestDiscount":"8.80", "highestDiscountReseller":"cardcash"},
    {"storeName":"Barney's New York", "id":"352", "url":"http://www.cardbear.com/gift-card-discount/352/Barney%27s+New+York", "highestDiscount":"8.60", "highestDiscountReseller":"cardcash"},
    {"storeName":"Baskin Robbins", "id":"60", "url":"http://www.cardbear.com/gift-card-discount/60/Baskin+Robbins", "highestDiscount":"15.60", "highestDiscountReseller":"cardcash"},
    {"storeName":"Bass Pro Shops", "id":"89", "url":"http://www.cardbear.com/gift-card-discount/89/Bass+Pro+Shops", "highestDiscount":"16.41", "highestDiscountReseller":"saveya"},
    {"storeName":"Bath & Body Works", "id":"115", "url":"http://www.cardbear.com/gift-card-discount/115/Bath+%26+Body+Works", "highestDiscount":"9.16", "highestDiscountReseller":"saveya"},
    {"storeName":"Bebe", "id":"253", "url":"http://www.cardbear.com/gift-card-discount/253/Bebe", "highestDiscount":"16.10", "highestDiscountReseller":"cardcash"},
    {"storeName":"Bed and Breakfast", "id":"78", "url":"http://www.cardbear.com/gift-card-discount/78/Bed+and+Breakfast", "highestDiscount":"30.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Bed Bath & Beyond", "id":"142", "url":"http://www.cardbear.com/gift-card-discount/142/Bed+Bath+%26+Beyond", "highestDiscount":"7.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Belk", "id":"63", "url":"http://www.cardbear.com/gift-card-discount/63/Belk", "highestDiscount":"18.50", "highestDiscountReseller":"cardcash"},
    {"storeName":"Ben & Jerry's", "id":"454", "url":"http://www.cardbear.com/gift-card-discount/454/Ben+%26+Jerry%27s", "highestDiscount":"25.00", "highestDiscountReseller":"raise"},
    {"storeName":"Benihana", "id":"413", "url":"http://www.cardbear.com/gift-card-discount/413/Benihana", "highestDiscount":"12.30", "highestDiscountReseller":"raise"},
    {"storeName":"Bennigan's", "id":"353", "url":"http://www.cardbear.com/gift-card-discount/353/Bennigan%27s", "highestDiscount":"3.00", "highestDiscountReseller":"raise"},
    {"storeName":"Bensi", "id":"354", "url":"http://www.cardbear.com/gift-card-discount/354/Bensi", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Bertucci's", "id":"162", "url":"http://www.cardbear.com/gift-card-discount/162/Bertucci%27s", "highestDiscount":"16.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Best Buy", "id":"12", "url":"http://www.cardbear.com/gift-card-discount/12/Best+Buy", "highestDiscount":"3.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Best Western", "id":"82", "url":"http://www.cardbear.com/gift-card-discount/82/Best+Western", "highestDiscount":"5.00", "highestDiscountReseller":"raise"},
    {"storeName":"BevMo", "id":"455", "url":"http://www.cardbear.com/gift-card-discount/455/BevMo", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Big 5", "id":"355", "url":"http://www.cardbear.com/gift-card-discount/355/Big+5", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Big Boy", "id":"356", "url":"http://www.cardbear.com/gift-card-discount/356/Big+Boy", "highestDiscount":"8.00", "highestDiscountReseller":"raise"},
    {"storeName":"Big Lots", "id":"401", "url":"http://www.cardbear.com/gift-card-discount/401/Big+Lots", "highestDiscount":"11.10", "highestDiscountReseller":"raise"},
    {"storeName":"Biggby Coffee", "id":"467", "url":"http://www.cardbear.com/gift-card-discount/467/Biggby+Coffee", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"BJ's Restaurant", "id":"399", "url":"http://www.cardbear.com/gift-card-discount/399/BJ%27s+Restaurant", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Black Angus Steakhouse", "id":"163", "url":"http://www.cardbear.com/gift-card-discount/163/Black+Angus+Steakhouse", "highestDiscount":"18.20", "highestDiscountReseller":"raise"},
    {"storeName":"Bloomingdale's", "id":"1", "url":"http://www.cardbear.com/gift-card-discount/1/Bloomingdale%27s", "highestDiscount":"10.50", "highestDiscountReseller":"saveya"},
    {"storeName":"Bob Evans", "id":"270", "url":"http://www.cardbear.com/gift-card-discount/270/Bob+Evans", "highestDiscount":"15.80", "highestDiscountReseller":"cardcash"},
    {"storeName":"Bon-Ton", "id":"241", "url":"http://www.cardbear.com/gift-card-discount/241/Bon-Ton", "highestDiscount":"11.10", "highestDiscountReseller":"cardcash"},
    {"storeName":"Bonefish Grill", "id":"141", "url":"http://www.cardbear.com/gift-card-discount/141/Bonefish+Grill", "highestDiscount":"15.00", "highestDiscountReseller":"raise"},
    {"storeName":"Boscov's", "id":"365", "url":"http://www.cardbear.com/gift-card-discount/365/Boscov%27s", "highestDiscount":"13.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Bose", "id":"349", "url":"http://www.cardbear.com/gift-card-discount/349/Bose", "highestDiscount":"17.00", "highestDiscountReseller":"raise"},
    {"storeName":"Boston Market", "id":"175", "url":"http://www.cardbear.com/gift-card-discount/175/Boston+Market", "highestDiscount":"19.78", "highestDiscountReseller":"saveya"},
    {"storeName":"Boston Store", "id":"164", "url":"http://www.cardbear.com/gift-card-discount/164/Boston+Store", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"BP", "id":"391", "url":"http://www.cardbear.com/gift-card-discount/391/BP", "highestDiscount":"1.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Bravo Brio", "id":"362", "url":"http://www.cardbear.com/gift-card-discount/362/Bravo+Brio", "highestDiscount":"19.48", "highestDiscountReseller":"saveya"},
    {"storeName":"Brooks Brothers", "id":"370", "url":"http://www.cardbear.com/gift-card-discount/370/Brooks+Brothers", "highestDiscount":"20.00", "highestDiscountReseller":"raise"},
    {"storeName":"Brookstone", "id":"24", "url":"http://www.cardbear.com/gift-card-discount/24/Brookstone", "highestDiscount":"15.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Bruster's Ice Cream", "id":"501", "url":"http://www.cardbear.com/gift-card-discount/501/Bruster%27s+Ice+Cream", "highestDiscount":"1.00", "highestDiscountReseller":"raise"},
    {"storeName":"Buca di Beppo", "id":"77", "url":"http://www.cardbear.com/gift-card-discount/77/Buca+di+Beppo", "highestDiscount":"25.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Bucketfeet", "id":"347", "url":"http://www.cardbear.com/gift-card-discount/347/Bucketfeet", "highestDiscount":"18.30", "highestDiscountReseller":"raise"},
    {"storeName":"Buckle", "id":"165", "url":"http://www.cardbear.com/gift-card-discount/165/Buckle", "highestDiscount":"20.50", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Buffalo Wild Wings", "id":"54", "url":"http://www.cardbear.com/gift-card-discount/54/Buffalo+Wild+Wings", "highestDiscount":"13.50", "highestDiscountReseller":"cardcash"},
    {"storeName":"Build-a-Bear", "id":"67", "url":"http://www.cardbear.com/gift-card-discount/67/Build-a-Bear", "highestDiscount":"32.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Burberry", "id":"221", "url":"http://www.cardbear.com/gift-card-discount/221/Burberry", "highestDiscount":"8.00", "highestDiscountReseller":"raise"},
    {"storeName":"Burger King", "id":"48", "url":"http://www.cardbear.com/gift-card-discount/48/Burger+King", "highestDiscount":"4.00", "highestDiscountReseller":"raise"},
    {"storeName":"Burlington Coat Factory", "id":"100", "url":"http://www.cardbear.com/gift-card-discount/100/Burlington+Coat+Factory", "highestDiscount":"4.00", "highestDiscountReseller":"raise"},
    {"storeName":"Buy Buy Baby", "id":"488", "url":"http://www.cardbear.com/gift-card-discount/488/Buy+Buy+Baby", "highestDiscount":"3.90", "highestDiscountReseller":"raise"},
    {"storeName":"Cabela's", "id":"86", "url":"http://www.cardbear.com/gift-card-discount/86/Cabela%27s", "highestDiscount":"12.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Cache", "id":"393", "url":"http://www.cardbear.com/gift-card-discount/393/Cache", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"California Pizza Kitchen", "id":"166", "url":"http://www.cardbear.com/gift-card-discount/166/California+Pizza+Kitchen", "highestDiscount":"24.10", "highestDiscountReseller":"raise"},
    {"storeName":"Calvin Klein", "id":"417", "url":"http://www.cardbear.com/gift-card-discount/417/Calvin+Klein", "highestDiscount":"5.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Caribou Coffee", "id":"383", "url":"http://www.cardbear.com/gift-card-discount/383/Caribou+Coffee", "highestDiscount":"12.70", "highestDiscountReseller":"cardcash"},
    {"storeName":"Carrabba's", "id":"239", "url":"http://www.cardbear.com/gift-card-discount/239/Carrabba%27s", "highestDiscount":"17.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Carrows", "id":"309", "url":"http://www.cardbear.com/gift-card-discount/309/Carrows", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Carter's", "id":"167", "url":"http://www.cardbear.com/gift-card-discount/167/Carter%27s", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Catherines", "id":"440", "url":"http://www.cardbear.com/gift-card-discount/440/Catherines", "highestDiscount":"25.00", "highestDiscountReseller":"raise"},
    {"storeName":"Cato", "id":"168", "url":"http://www.cardbear.com/gift-card-discount/168/Cato", "highestDiscount":"25.90", "highestDiscountReseller":"saveya"},
    {"storeName":"Cavender's", "id":"316", "url":"http://www.cardbear.com/gift-card-discount/316/Cavender%27s", "highestDiscount":"19.20", "highestDiscountReseller":"raise"},
    {"storeName":"Champs Sports", "id":"400", "url":"http://www.cardbear.com/gift-card-discount/400/Champs+Sports", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Charlotte Russe", "id":"79", "url":"http://www.cardbear.com/gift-card-discount/79/Charlotte+Russe", "highestDiscount":"32.50", "highestDiscountReseller":"raise"},
    {"storeName":"Cheeseburger in Paradise", "id":"338", "url":"http://www.cardbear.com/gift-card-discount/338/Cheeseburger+in+Paradise", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Cheesecake Factory", "id":"61", "url":"http://www.cardbear.com/gift-card-discount/61/Cheesecake+Factory", "highestDiscount":"12.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Chevron", "id":"468", "url":"http://www.cardbear.com/gift-card-discount/468/Chevron", "highestDiscount":"4.50", "highestDiscountReseller":"saveya"},
    {"storeName":"Chevys Fresh Mex", "id":"457", "url":"http://www.cardbear.com/gift-card-discount/457/Chevys+Fresh+Mex", "highestDiscount":"29.20", "highestDiscountReseller":"raise"},
    {"storeName":"Chick-fil-A", "id":"334", "url":"http://www.cardbear.com/gift-card-discount/334/Chick-fil-A", "highestDiscount":"5.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Chico's", "id":"441", "url":"http://www.cardbear.com/gift-card-discount/441/Chico%27s", "highestDiscount":"24.70", "highestDiscountReseller":"raise"},
    {"storeName":"Children's Place", "id":"122", "url":"http://www.cardbear.com/gift-card-discount/122/Children%27s+Place", "highestDiscount":"15.40", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Chili's", "id":"58", "url":"http://www.cardbear.com/gift-card-discount/58/Chili%27s", "highestDiscount":"20.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Chipotle", "id":"106", "url":"http://www.cardbear.com/gift-card-discount/106/Chipotle", "highestDiscount":"10.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Christopher & Banks", "id":"474", "url":"http://www.cardbear.com/gift-card-discount/474/Christopher+%26+Banks", "highestDiscount":"28.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"Chuck E Cheese's", "id":"302", "url":"http://www.cardbear.com/gift-card-discount/302/Chuck+E+Cheese%27s", "highestDiscount":"11.30", "highestDiscountReseller":"cardcash"},
    {"storeName":"Cinema De Lux", "id":"301", "url":"http://www.cardbear.com/gift-card-discount/301/Cinema+De+Lux", "highestDiscount":"35.60", "highestDiscountReseller":"cardcash"},
    {"storeName":"Cinemark", "id":"300", "url":"http://www.cardbear.com/gift-card-discount/300/Cinemark", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Cirque du Soleil", "id":"261", "url":"http://www.cardbear.com/gift-card-discount/261/Cirque+du+Soleil", "highestDiscount":"10.00", "highestDiscountReseller":"raise"},
    {"storeName":"Citgo", "id":"340", "url":"http://www.cardbear.com/gift-card-discount/340/Citgo", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Claim Jumper", "id":"245", "url":"http://www.cardbear.com/gift-card-discount/245/Claim+Jumper", "highestDiscount":"17.20", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Claire's", "id":"97", "url":"http://www.cardbear.com/gift-card-discount/97/Claire%27s", "highestDiscount":"38.10", "highestDiscountReseller":"raise"},
    {"storeName":"Clarks", "id":"386", "url":"http://www.cardbear.com/gift-card-discount/386/Clarks", "highestDiscount":"14.50", "highestDiscountReseller":"raise"},
    {"storeName":"Club Monaco", "id":"224", "url":"http://www.cardbear.com/gift-card-discount/224/Club+Monaco", "highestDiscount":"18.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"Coach", "id":"169", "url":"http://www.cardbear.com/gift-card-discount/169/Coach", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Coffee Bean & Tea Leaf", "id":"118", "url":"http://www.cardbear.com/gift-card-discount/118/Coffee+Bean+%26+Tea+Leaf", "highestDiscount":"30.35", "highestDiscountReseller":"cardcash"},
    {"storeName":"Cold Stone Creamery", "id":"59", "url":"http://www.cardbear.com/gift-card-discount/59/Cold+Stone+Creamery", "highestDiscount":"28.82", "highestDiscountReseller":"cardcash"},
    {"storeName":"Cole Haan", "id":"92", "url":"http://www.cardbear.com/gift-card-discount/92/Cole+Haan", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Columbia", "id":"304", "url":"http://www.cardbear.com/gift-card-discount/304/Columbia", "highestDiscount":"10.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Conoco Gas", "id":"506", "url":"http://www.cardbear.com/gift-card-discount/506/Conoco+Gas", "highestDiscount":"2.00", "highestDiscountReseller":"raise"},
    {"storeName":"Container Store", "id":"510", "url":"http://www.cardbear.com/gift-card-discount/510/Container+Store", "highestDiscount":"8.49", "highestDiscountReseller":"saveya"},
    {"storeName":"Converse", "id":"93", "url":"http://www.cardbear.com/gift-card-discount/93/Converse", "highestDiscount":"1.40", "highestDiscountReseller":"raise"},
    {"storeName":"Cost Plus World Market", "id":"418", "url":"http://www.cardbear.com/gift-card-discount/418/Cost+Plus+World+Market", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Cracker Barrel", "id":"170", "url":"http://www.cardbear.com/gift-card-discount/170/Cracker+Barrel", "highestDiscount":"17.81", "highestDiscountReseller":"saveya"},
    {"storeName":"Crate & Barrel", "id":"171", "url":"http://www.cardbear.com/gift-card-discount/171/Crate+%26+Barrel", "highestDiscount":"5.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Crazy 8", "id":"172", "url":"http://www.cardbear.com/gift-card-discount/172/Crazy+8", "highestDiscount":"25.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Crocs", "id":"252", "url":"http://www.cardbear.com/gift-card-discount/252/Crocs", "highestDiscount":"5.50", "highestDiscountReseller":"cardcash"},
    {"storeName":"Crutchfield", "id":"298", "url":"http://www.cardbear.com/gift-card-discount/298/Crutchfield", "highestDiscount":"1.00", "highestDiscountReseller":"raise"},
    {"storeName":"CVS", "id":"107", "url":"http://www.cardbear.com/gift-card-discount/107/CVS", "highestDiscount":"11.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Dairy Queen", "id":"382", "url":"http://www.cardbear.com/gift-card-discount/382/Dairy+Queen", "highestDiscount":"10.40", "highestDiscountReseller":"cardcash"},
    {"storeName":"Damon's Grill", "id":"208", "url":"http://www.cardbear.com/gift-card-discount/208/Damon%27s+Grill", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Darden Restaurants", "id":"307", "url":"http://www.cardbear.com/gift-card-discount/307/Darden+Restaurants", "highestDiscount":"15.51", "highestDiscountReseller":"saveya"},
    {"storeName":"Dave and Busters", "id":"220", "url":"http://www.cardbear.com/gift-card-discount/220/Dave+and+Busters", "highestDiscount":"19.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"David's Bridal", "id":"499", "url":"http://www.cardbear.com/gift-card-discount/499/David%27s+Bridal", "highestDiscount":"18.90", "highestDiscountReseller":"raise"},
    {"storeName":"Dean & Deluca", "id":"209", "url":"http://www.cardbear.com/gift-card-discount/209/Dean+%26+Deluca", "highestDiscount":"30.03", "highestDiscountReseller":"cardcash"},
    {"storeName":"Del Taco", "id":"327", "url":"http://www.cardbear.com/gift-card-discount/327/Del+Taco", "highestDiscount":"12.00", "highestDiscountReseller":"raise"},
    {"storeName":"dELiA's", "id":"204", "url":"http://www.cardbear.com/gift-card-discount/204/dELiA%27s", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Dell", "id":"39", "url":"http://www.cardbear.com/gift-card-discount/39/Dell", "highestDiscount":"6.50", "highestDiscountReseller":"cardpool"},
    {"storeName":"Delta Airlines", "id":"331", "url":"http://www.cardbear.com/gift-card-discount/331/Delta+Airlines", "highestDiscount":"4.50", "highestDiscountReseller":"raise"},
    {"storeName":"Denny's", "id":"289", "url":"http://www.cardbear.com/gift-card-discount/289/Denny%27s", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Dick's Sporting Goods", "id":"81", "url":"http://www.cardbear.com/gift-card-discount/81/Dick%27s+Sporting+Goods", "highestDiscount":"13.41", "highestDiscountReseller":"saveya"},
    {"storeName":"Diesel", "id":"465", "url":"http://www.cardbear.com/gift-card-discount/465/Diesel", "highestDiscount":"21.00", "highestDiscountReseller":"raise"},
    {"storeName":"Dillard's", "id":"227", "url":"http://www.cardbear.com/gift-card-discount/227/Dillard%27s", "highestDiscount":"15.01", "highestDiscountReseller":"saveya"},
    {"storeName":"Discovery Channel Store", "id":"101", "url":"http://www.cardbear.com/gift-card-discount/101/Discovery+Channel+Store", "highestDiscount":"15.10", "highestDiscountReseller":"raise"},
    {"storeName":"Disney Store", "id":"57", "url":"http://www.cardbear.com/gift-card-discount/57/Disney+Store", "highestDiscount":"8.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Disney World Resort", "id":"65", "url":"http://www.cardbear.com/gift-card-discount/65/Disney+World+Resort", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"DKNY", "id":"484", "url":"http://www.cardbear.com/gift-card-discount/484/DKNY", "highestDiscount":"13.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Domino's Pizza", "id":"33", "url":"http://www.cardbear.com/gift-card-discount/33/Domino%27s+Pizza", "highestDiscount":"10.10", "highestDiscountReseller":"raise"},
    {"storeName":"Dressbarn", "id":"87", "url":"http://www.cardbear.com/gift-card-discount/87/Dressbarn", "highestDiscount":"30.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"DSW", "id":"88", "url":"http://www.cardbear.com/gift-card-discount/88/DSW", "highestDiscount":"14.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Dunkin Donuts", "id":"103", "url":"http://www.cardbear.com/gift-card-discount/103/Dunkin+Donuts", "highestDiscount":"10.23", "highestDiscountReseller":"cardcash"},
    {"storeName":"Dunn Bros", "id":"466", "url":"http://www.cardbear.com/gift-card-discount/466/Dunn+Bros", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"eBay", "id":"344", "url":"http://www.cardbear.com/gift-card-discount/344/eBay", "highestDiscount":"2.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Ecco", "id":"392", "url":"http://www.cardbear.com/gift-card-discount/392/Ecco", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Ecko Unltd", "id":"394", "url":"http://www.cardbear.com/gift-card-discount/394/Ecko+Unltd", "highestDiscount":"21.41", "highestDiscountReseller":"cardcash"},
    {"storeName":"Eddie Bauer", "id":"384", "url":"http://www.cardbear.com/gift-card-discount/384/Eddie+Bauer", "highestDiscount":"24.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Einstein Bros Bagels", "id":"210", "url":"http://www.cardbear.com/gift-card-discount/210/Einstein+Bros+Bagels", "highestDiscount":"17.31", "highestDiscountReseller":"cardcash"},
    {"storeName":"El Pollo Loco", "id":"410", "url":"http://www.cardbear.com/gift-card-discount/410/El+Pollo+Loco", "highestDiscount":"10.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Elephant Bar", "id":"295", "url":"http://www.cardbear.com/gift-card-discount/295/Elephant+Bar", "highestDiscount":"24.50", "highestDiscountReseller":"raise"},
    {"storeName":"Express", "id":"7", "url":"http://www.cardbear.com/gift-card-discount/7/Express", "highestDiscount":"20.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"Exxon Mobil", "id":"379", "url":"http://www.cardbear.com/gift-card-discount/379/Exxon+Mobil", "highestDiscount":"3.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Family Dollar", "id":"322", "url":"http://www.cardbear.com/gift-card-discount/322/Family+Dollar", "highestDiscount":"13.10", "highestDiscountReseller":"raise"},
    {"storeName":"Famous Footwear", "id":"320", "url":"http://www.cardbear.com/gift-card-discount/320/Famous+Footwear", "highestDiscount":"8.30", "highestDiscountReseller":"raise"},
    {"storeName":"Fandango", "id":"114", "url":"http://www.cardbear.com/gift-card-discount/114/Fandango", "highestDiscount":"17.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Fannie May", "id":"497", "url":"http://www.cardbear.com/gift-card-discount/497/Fannie+May", "highestDiscount":"23.10", "highestDiscountReseller":"cardcash"},
    {"storeName":"Finish Line", "id":"445", "url":"http://www.cardbear.com/gift-card-discount/445/Finish+Line", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Five Below", "id":"271", "url":"http://www.cardbear.com/gift-card-discount/271/Five+Below", "highestDiscount":"15.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Five Guys", "id":"236", "url":"http://www.cardbear.com/gift-card-discount/236/Five+Guys", "highestDiscount":"20.00", "highestDiscountReseller":"raise"},
    {"storeName":"Fleming's", "id":"205", "url":"http://www.cardbear.com/gift-card-discount/205/Fleming%27s", "highestDiscount":"20.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Fogo De Chao", "id":"176", "url":"http://www.cardbear.com/gift-card-discount/176/Fogo+De+Chao", "highestDiscount":"18.40", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Foot Locker", "id":"230", "url":"http://www.cardbear.com/gift-card-discount/230/Foot+Locker", "highestDiscount":"9.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Forever 21", "id":"173", "url":"http://www.cardbear.com/gift-card-discount/173/Forever+21", "highestDiscount":"23.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Forever Yogurt", "id":"279", "url":"http://www.cardbear.com/gift-card-discount/279/Forever+Yogurt", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Fossil", "id":"203", "url":"http://www.cardbear.com/gift-card-discount/203/Fossil", "highestDiscount":"22.90", "highestDiscountReseller":"cardcash"},
    {"storeName":"Four Seasons", "id":"281", "url":"http://www.cardbear.com/gift-card-discount/281/Four+Seasons", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Frederick's of Hollywood", "id":"450", "url":"http://www.cardbear.com/gift-card-discount/450/Frederick%27s+of+Hollywood", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Free People", "id":"493", "url":"http://www.cardbear.com/gift-card-discount/493/Free+People", "highestDiscount":"14.79", "highestDiscountReseller":"saveya"},
    {"storeName":"Frontier Airlines", "id":"330", "url":"http://www.cardbear.com/gift-card-discount/330/Frontier+Airlines", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Fuddruckers", "id":"447", "url":"http://www.cardbear.com/gift-card-discount/447/Fuddruckers", "highestDiscount":"12.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"FYE", "id":"211", "url":"http://www.cardbear.com/gift-card-discount/211/FYE", "highestDiscount":"15.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"G.H. Bass & Co", "id":"446", "url":"http://www.cardbear.com/gift-card-discount/446/G.H.+Bass+%26+Co", "highestDiscount":"15.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Gabriel Brothers", "id":"345", "url":"http://www.cardbear.com/gift-card-discount/345/Gabriel+Brothers", "highestDiscount":"6.00", "highestDiscountReseller":"raise"},
    {"storeName":"GameStop", "id":"137", "url":"http://www.cardbear.com/gift-card-discount/137/GameStop", "highestDiscount":"10.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Gander Mountain", "id":"487", "url":"http://www.cardbear.com/gift-card-discount/487/Gander+Mountain", "highestDiscount":"7.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Gap", "id":"124", "url":"http://www.cardbear.com/gift-card-discount/124/Gap", "highestDiscount":"11.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Garrett Popcorn", "id":"343", "url":"http://www.cardbear.com/gift-card-discount/343/Garrett+Popcorn", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Gilt", "id":"462", "url":"http://www.cardbear.com/gift-card-discount/462/Gilt", "highestDiscount":"10.00", "highestDiscountReseller":"raise"},
    {"storeName":"Global Hotel Card", "id":"359", "url":"http://www.cardbear.com/gift-card-discount/359/Global+Hotel+Card", "highestDiscount":"22.00", "highestDiscountReseller":"raise"},
    {"storeName":"GNC", "id":"156", "url":"http://www.cardbear.com/gift-card-discount/156/GNC", "highestDiscount":"8.60", "highestDiscountReseller":"cardcash"},
    {"storeName":"Godiva", "id":"286", "url":"http://www.cardbear.com/gift-card-discount/286/Godiva", "highestDiscount":"21.00", "highestDiscountReseller":"raise"},
    {"storeName":"Golden Corral", "id":"456", "url":"http://www.cardbear.com/gift-card-discount/456/Golden+Corral", "highestDiscount":"10.10", "highestDiscountReseller":"cardcash"},
    {"storeName":"Golf Galaxy", "id":"305", "url":"http://www.cardbear.com/gift-card-discount/305/Golf+Galaxy", "highestDiscount":"17.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Golfsmith", "id":"257", "url":"http://www.cardbear.com/gift-card-discount/257/Golfsmith", "highestDiscount":"12.01", "highestDiscountReseller":"saveya"},
    {"storeName":"GolfThere", "id":"357", "url":"http://www.cardbear.com/gift-card-discount/357/GolfThere", "highestDiscount":"28.00", "highestDiscountReseller":"raise"},
    {"storeName":"Google Play", "id":"225", "url":"http://www.cardbear.com/gift-card-discount/225/Google+Play", "highestDiscount":"7.00", "highestDiscountReseller":"raise"},
    {"storeName":"Gordmans", "id":"473", "url":"http://www.cardbear.com/gift-card-discount/473/Gordmans", "highestDiscount":"28.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Groupon", "id":"428", "url":"http://www.cardbear.com/gift-card-discount/428/Groupon", "highestDiscount":"1.00", "highestDiscountReseller":"raise"},
    {"storeName":"Gucci", "id":"223", "url":"http://www.cardbear.com/gift-card-discount/223/Gucci", "highestDiscount":"0.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Guess", "id":"202", "url":"http://www.cardbear.com/gift-card-discount/202/Guess", "highestDiscount":"9.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Guitar Center", "id":"299", "url":"http://www.cardbear.com/gift-card-discount/299/Guitar+Center", "highestDiscount":"10.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Gymboree", "id":"306", "url":"http://www.cardbear.com/gift-card-discount/306/Gymboree", "highestDiscount":"28.95", "highestDiscountReseller":"saveya"},
    {"storeName":"H&M", "id":"14", "url":"http://www.cardbear.com/gift-card-discount/14/H%26M", "highestDiscount":"32.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Haagen Dazs", "id":"273", "url":"http://www.cardbear.com/gift-card-discount/273/Haagen+Dazs", "highestDiscount":"10.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Habit Burger", "id":"277", "url":"http://www.cardbear.com/gift-card-discount/277/Habit+Burger", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Hallmark", "id":"98", "url":"http://www.cardbear.com/gift-card-discount/98/Hallmark", "highestDiscount":"6.50", "highestDiscountReseller":"cardcash"},
    {"storeName":"Hancock Fabrics", "id":"247", "url":"http://www.cardbear.com/gift-card-discount/247/Hancock+Fabrics", "highestDiscount":"7.00", "highestDiscountReseller":"raise"},
    {"storeName":"Harbor Freight Tools", "id":"512", "url":"http://www.cardbear.com/gift-card-discount/512/Harbor+Freight+Tools", "highestDiscount":"14.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Hard Rock Cafe", "id":"287", "url":"http://www.cardbear.com/gift-card-discount/287/Hard+Rock+Cafe", "highestDiscount":"6.00", "highestDiscountReseller":"raise"},
    {"storeName":"Harry & David", "id":"157", "url":"http://www.cardbear.com/gift-card-discount/157/Harry+%26+David", "highestDiscount":"34.90", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Hawaiian Airlines", "id":"184", "url":"http://www.cardbear.com/gift-card-discount/184/Hawaiian+Airlines", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Hess", "id":"495", "url":"http://www.cardbear.com/gift-card-discount/495/Hess", "highestDiscount":"4.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"hh gregg", "id":"375", "url":"http://www.cardbear.com/gift-card-discount/375/hh+gregg", "highestDiscount":"6.98", "highestDiscountReseller":"cardcash"},
    {"storeName":"Hobby Lobby", "id":"451", "url":"http://www.cardbear.com/gift-card-discount/451/Hobby+Lobby", "highestDiscount":"15.60", "highestDiscountReseller":"cardcash"},
    {"storeName":"Hollister", "id":"121", "url":"http://www.cardbear.com/gift-card-discount/121/Hollister", "highestDiscount":"25.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Home Depot", "id":"2", "url":"http://www.cardbear.com/gift-card-discount/2/Home+Depot", "highestDiscount":"9.94", "highestDiscountReseller":"cardcash"},
    {"storeName":"HomeGoods", "id":"80", "url":"http://www.cardbear.com/gift-card-discount/80/HomeGoods", "highestDiscount":"12.00", "highestDiscountReseller":"raise"},
    {"storeName":"HoneyBaked Ham", "id":"439", "url":"http://www.cardbear.com/gift-card-discount/439/HoneyBaked+Ham", "highestDiscount":"25.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Hooters", "id":"294", "url":"http://www.cardbear.com/gift-card-discount/294/Hooters", "highestDiscount":"15.00", "highestDiscountReseller":"raise"},
    {"storeName":"Hot Topic", "id":"140", "url":"http://www.cardbear.com/gift-card-discount/140/Hot+Topic", "highestDiscount":"10.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Hotels.com", "id":"470", "url":"http://www.cardbear.com/gift-card-discount/470/Hotels.com", "highestDiscount":"6.00", "highestDiscountReseller":"raise"},
    {"storeName":"HP", "id":"511", "url":"http://www.cardbear.com/gift-card-discount/511/HP", "highestDiscount":"10.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Hugo Boss", "id":"369", "url":"http://www.cardbear.com/gift-card-discount/369/Hugo+Boss", "highestDiscount":"5.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Hyatt", "id":"280", "url":"http://www.cardbear.com/gift-card-discount/280/Hyatt", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"IHOP", "id":"51", "url":"http://www.cardbear.com/gift-card-discount/51/IHOP", "highestDiscount":"10.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Ikea", "id":"217", "url":"http://www.cardbear.com/gift-card-discount/217/Ikea", "highestDiscount":"5.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"J Crew", "id":"377", "url":"http://www.cardbear.com/gift-card-discount/377/J+Crew", "highestDiscount":"10.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Jack in the Box", "id":"411", "url":"http://www.cardbear.com/gift-card-discount/411/Jack+in+the+Box", "highestDiscount":"23.10", "highestDiscountReseller":"raise"},
    {"storeName":"Jamba Juice", "id":"174", "url":"http://www.cardbear.com/gift-card-discount/174/Jamba+Juice", "highestDiscount":"29.70", "highestDiscountReseller":"raise"},
    {"storeName":"Janie and Jack", "id":"374", "url":"http://www.cardbear.com/gift-card-discount/374/Janie+and+Jack", "highestDiscount":"20.60", "highestDiscountReseller":"cardcash"},
    {"storeName":"Jared", "id":"502", "url":"http://www.cardbear.com/gift-card-discount/502/Jared", "highestDiscount":"12.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"JCPenney", "id":"120", "url":"http://www.cardbear.com/gift-card-discount/120/JCPenney", "highestDiscount":"15.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"JetBlue Airline", "id":"255", "url":"http://www.cardbear.com/gift-card-discount/255/JetBlue+Airline", "highestDiscount":"5.75", "highestDiscountReseller":"cardcash"},
    {"storeName":"Jiffy Lube", "id":"427", "url":"http://www.cardbear.com/gift-card-discount/427/Jiffy+Lube", "highestDiscount":"10.36", "highestDiscountReseller":"cardcash"},
    {"storeName":"Jimmy John's", "id":"436", "url":"http://www.cardbear.com/gift-card-discount/436/Jimmy+John%27s", "highestDiscount":"16.74", "highestDiscountReseller":"cardcash"},
    {"storeName":"Jo Ann", "id":"251", "url":"http://www.cardbear.com/gift-card-discount/251/Jo+Ann", "highestDiscount":"10.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Johnny Rockets", "id":"420", "url":"http://www.cardbear.com/gift-card-discount/420/Johnny+Rockets", "highestDiscount":"10.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Jos A Bank", "id":"201", "url":"http://www.cardbear.com/gift-card-discount/201/Jos+A+Bank", "highestDiscount":"20.40", "highestDiscountReseller":"raise"},
    {"storeName":"Journeys", "id":"415", "url":"http://www.cardbear.com/gift-card-discount/415/Journeys", "highestDiscount":"11.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Justice", "id":"95", "url":"http://www.cardbear.com/gift-card-discount/95/Justice", "highestDiscount":"27.08", "highestDiscountReseller":"cardcash"},
    {"storeName":"Kate Spade", "id":"259", "url":"http://www.cardbear.com/gift-card-discount/259/Kate+Spade", "highestDiscount":"8.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Kay Jewelers", "id":"71", "url":"http://www.cardbear.com/gift-card-discount/71/Kay+Jewelers", "highestDiscount":"19.90", "highestDiscountReseller":"cardcash"},
    {"storeName":"Kenneth Cole", "id":"291", "url":"http://www.cardbear.com/gift-card-discount/291/Kenneth+Cole", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"KFC", "id":"422", "url":"http://www.cardbear.com/gift-card-discount/422/KFC", "highestDiscount":"11.10", "highestDiscountReseller":"raise"},
    {"storeName":"Kiehl's", "id":"308", "url":"http://www.cardbear.com/gift-card-discount/308/Kiehl%27s", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Kirkland's", "id":"256", "url":"http://www.cardbear.com/gift-card-discount/256/Kirkland%27s", "highestDiscount":"2.10", "highestDiscountReseller":"raise"},
    {"storeName":"Kmart", "id":"28", "url":"http://www.cardbear.com/gift-card-discount/28/Kmart", "highestDiscount":"5.80", "highestDiscountReseller":"raise"},
    {"storeName":"Kohl's", "id":"128", "url":"http://www.cardbear.com/gift-card-discount/128/Kohl%27s", "highestDiscount":"9.50", "highestDiscountReseller":"cardpool"},
    {"storeName":"Krispy Kreme", "id":"152", "url":"http://www.cardbear.com/gift-card-discount/152/Krispy+Kreme", "highestDiscount":"15.70", "highestDiscountReseller":"cardcash"},
    {"storeName":"Kroger", "id":"90", "url":"http://www.cardbear.com/gift-card-discount/90/Kroger", "highestDiscount":"2.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"L.A. Tan", "id":"430", "url":"http://www.cardbear.com/gift-card-discount/430/L.A.+Tan", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"L.L.Bean", "id":"74", "url":"http://www.cardbear.com/gift-card-discount/74/L.L.Bean", "highestDiscount":"13.10", "highestDiscountReseller":"cardcash"},
    {"storeName":"Lacoste", "id":"200", "url":"http://www.cardbear.com/gift-card-discount/200/Lacoste", "highestDiscount":"10.50", "highestDiscountReseller":"cardcash"},
    {"storeName":"Lady Foot Locker", "id":"504", "url":"http://www.cardbear.com/gift-card-discount/504/Lady+Foot+Locker", "highestDiscount":"5.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Lands' End", "id":"213", "url":"http://www.cardbear.com/gift-card-discount/213/Lands%27+End", "highestDiscount":"5.00", "highestDiscountReseller":"raise"},
    {"storeName":"Lane Bryant", "id":"243", "url":"http://www.cardbear.com/gift-card-discount/243/Lane+Bryant", "highestDiscount":"35.00", "highestDiscountReseller":"raise"},
    {"storeName":"Legal Sea Foods", "id":"207", "url":"http://www.cardbear.com/gift-card-discount/207/Legal+Sea+Foods", "highestDiscount":"30.02", "highestDiscountReseller":"saveya"},
    {"storeName":"Lego", "id":"138", "url":"http://www.cardbear.com/gift-card-discount/138/Lego", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Lettuce Entertain You", "id":"366", "url":"http://www.cardbear.com/gift-card-discount/366/Lettuce+Entertain+You", "highestDiscount":"15.49", "highestDiscountReseller":"cardcash"},
    {"storeName":"Levi's", "id":"403", "url":"http://www.cardbear.com/gift-card-discount/403/Levi%27s", "highestDiscount":"16.60", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Lids", "id":"264", "url":"http://www.cardbear.com/gift-card-discount/264/Lids", "highestDiscount":"2.00", "highestDiscountReseller":"raise"},
    {"storeName":"Limited", "id":"116", "url":"http://www.cardbear.com/gift-card-discount/116/Limited", "highestDiscount":"25.70", "highestDiscountReseller":"cardcash"},
    {"storeName":"Loews Cineplex", "id":"337", "url":"http://www.cardbear.com/gift-card-discount/337/Loews+Cineplex", "highestDiscount":"10.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Loft", "id":"376", "url":"http://www.cardbear.com/gift-card-discount/376/Loft", "highestDiscount":"27.09", "highestDiscountReseller":"cardcash"},
    {"storeName":"Logan's Roadhouse", "id":"26", "url":"http://www.cardbear.com/gift-card-discount/26/Logan%27s+Roadhouse", "highestDiscount":"12.00", "highestDiscountReseller":"raise"},
    {"storeName":"Lone Star Steakhouse", "id":"206", "url":"http://www.cardbear.com/gift-card-discount/206/Lone+Star+Steakhouse", "highestDiscount":"21.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Long John Silver's", "id":"419", "url":"http://www.cardbear.com/gift-card-discount/419/Long+John+Silver%27s", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Longhorn Steakhouse", "id":"55", "url":"http://www.cardbear.com/gift-card-discount/55/Longhorn+Steakhouse", "highestDiscount":"16.12", "highestDiscountReseller":"saveya"},
    {"storeName":"Lord & Taylor", "id":"139", "url":"http://www.cardbear.com/gift-card-discount/139/Lord+%26+Taylor", "highestDiscount":"12.50", "highestDiscountReseller":"cardcash"},
    {"storeName":"Louis Vuitton", "id":"235", "url":"http://www.cardbear.com/gift-card-discount/235/Louis+Vuitton", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Lowe's", "id":"19", "url":"http://www.cardbear.com/gift-card-discount/19/Lowe%27s", "highestDiscount":"6.40", "highestDiscountReseller":"raise"},
    {"storeName":"Lucille's BBQ", "id":"258", "url":"http://www.cardbear.com/gift-card-discount/258/Lucille%27s+BBQ", "highestDiscount":"19.87", "highestDiscountReseller":"cardcash"},
    {"storeName":"Lucky Brand", "id":"199", "url":"http://www.cardbear.com/gift-card-discount/199/Lucky+Brand", "highestDiscount":"30.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Lululemon", "id":"385", "url":"http://www.cardbear.com/gift-card-discount/385/Lululemon", "highestDiscount":"10.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Lush", "id":"288", "url":"http://www.cardbear.com/gift-card-discount/288/Lush", "highestDiscount":"25.00", "highestDiscountReseller":"raise"},
    {"storeName":"MAC", "id":"318", "url":"http://www.cardbear.com/gift-card-discount/318/MAC", "highestDiscount":"11.50", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Macaroni Grill", "id":"192", "url":"http://www.cardbear.com/gift-card-discount/192/Macaroni+Grill", "highestDiscount":"17.30", "highestDiscountReseller":"raise"},
    {"storeName":"Macy's", "id":"15", "url":"http://www.cardbear.com/gift-card-discount/15/Macy%27s", "highestDiscount":"10.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"Magazines.com", "id":"64", "url":"http://www.cardbear.com/gift-card-discount/64/Magazines.com", "highestDiscount":"33.30", "highestDiscountReseller":"raise"},
    {"storeName":"Maggiano's", "id":"66", "url":"http://www.cardbear.com/gift-card-discount/66/Maggiano%27s", "highestDiscount":"13.10", "highestDiscountReseller":"raise"},
    {"storeName":"Mandee", "id":"315", "url":"http://www.cardbear.com/gift-card-discount/315/Mandee", "highestDiscount":"41.26", "highestDiscountReseller":"cardcash"},
    {"storeName":"Marcus Theatres", "id":"311", "url":"http://www.cardbear.com/gift-card-discount/311/Marcus+Theatres", "highestDiscount":"15.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Marriott", "id":"314", "url":"http://www.cardbear.com/gift-card-discount/314/Marriott", "highestDiscount":"0.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Marshalls", "id":"32", "url":"http://www.cardbear.com/gift-card-discount/32/Marshalls", "highestDiscount":"13.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Massage Envy", "id":"242", "url":"http://www.cardbear.com/gift-card-discount/242/Massage+Envy", "highestDiscount":"31.70", "highestDiscountReseller":"cardcash"},
    {"storeName":"Maurices", "id":"198", "url":"http://www.cardbear.com/gift-card-discount/198/Maurices", "highestDiscount":"21.80", "highestDiscountReseller":"cardcash"},
    {"storeName":"Max & Erma's", "id":"500", "url":"http://www.cardbear.com/gift-card-discount/500/Max+%26+Erma%27s", "highestDiscount":"15.00", "highestDiscountReseller":"raise"},
    {"storeName":"MC Sports", "id":"319", "url":"http://www.cardbear.com/gift-card-discount/319/MC+Sports", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"McCormick & Schmick's", "id":"293", "url":"http://www.cardbear.com/gift-card-discount/293/McCormick+%26+Schmick%27s", "highestDiscount":"20.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"McDonald's", "id":"62", "url":"http://www.cardbear.com/gift-card-discount/62/McDonald%27s", "highestDiscount":"16.60", "highestDiscountReseller":"raise"},
    {"storeName":"Meijer", "id":"350", "url":"http://www.cardbear.com/gift-card-discount/350/Meijer", "highestDiscount":"1.10", "highestDiscountReseller":"raise"},
    {"storeName":"Melting Pot", "id":"453", "url":"http://www.cardbear.com/gift-card-discount/453/Melting+Pot", "highestDiscount":"17.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"Men's Wearhouse", "id":"336", "url":"http://www.cardbear.com/gift-card-discount/336/Men%27s+Wearhouse", "highestDiscount":"17.31", "highestDiscountReseller":"saveya"},
    {"storeName":"Menards", "id":"317", "url":"http://www.cardbear.com/gift-card-discount/317/Menards", "highestDiscount":"0.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Mi Pueblo Foods", "id":"464", "url":"http://www.cardbear.com/gift-card-discount/464/Mi+Pueblo+Foods", "highestDiscount":"20.00", "highestDiscountReseller":"raise"},
    {"storeName":"Michael Kors", "id":"275", "url":"http://www.cardbear.com/gift-card-discount/275/Michael+Kors", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Michaels", "id":"17", "url":"http://www.cardbear.com/gift-card-discount/17/Michaels", "highestDiscount":"27.81", "highestDiscountReseller":"saveya"},
    {"storeName":"Microsoft Store", "id":"358", "url":"http://www.cardbear.com/gift-card-discount/358/Microsoft+Store", "highestDiscount":"13.00", "highestDiscountReseller":"raise"},
    {"storeName":"Mimi's Cafe", "id":"458", "url":"http://www.cardbear.com/gift-card-discount/458/Mimi%27s+Cafe", "highestDiscount":"10.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Miracle Mile Shops", "id":"324", "url":"http://www.cardbear.com/gift-card-discount/324/Miracle+Mile+Shops", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"MLB.com", "id":"431", "url":"http://www.cardbear.com/gift-card-discount/431/MLB.com", "highestDiscount":"12.00", "highestDiscountReseller":"raise"},
    {"storeName":"Modell's", "id":"476", "url":"http://www.cardbear.com/gift-card-discount/476/Modell%27s", "highestDiscount":"22.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Morton's Steakhouse", "id":"479", "url":"http://www.cardbear.com/gift-card-discount/479/Morton%27s+Steakhouse", "highestDiscount":"15.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Motherhood Maternity", "id":"197", "url":"http://www.cardbear.com/gift-card-discount/197/Motherhood+Maternity", "highestDiscount":"17.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Nascar Superstore", "id":"409", "url":"http://www.cardbear.com/gift-card-discount/409/Nascar+Superstore", "highestDiscount":"29.41", "highestDiscountReseller":"cardcash"},
    {"storeName":"Nautica", "id":"513", "url":"http://www.cardbear.com/gift-card-discount/513/Nautica", "highestDiscount":"32.30", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"NBA Store", "id":"398", "url":"http://www.cardbear.com/gift-card-discount/398/NBA+Store", "highestDiscount":"13.75", "highestDiscountReseller":"cardcash"},
    {"storeName":"Neiman Marcus", "id":"263", "url":"http://www.cardbear.com/gift-card-discount/263/Neiman+Marcus", "highestDiscount":"3.00", "highestDiscountReseller":"raise"},
    {"storeName":"Netflix", "id":"469", "url":"http://www.cardbear.com/gift-card-discount/469/Netflix", "highestDiscount":"1.00", "highestDiscountReseller":"raise"},
    {"storeName":"New Balance", "id":"461", "url":"http://www.cardbear.com/gift-card-discount/461/New+Balance", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"New Seasons Market", "id":"452", "url":"http://www.cardbear.com/gift-card-discount/452/New+Seasons+Market", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"New York & Company", "id":"136", "url":"http://www.cardbear.com/gift-card-discount/136/New+York+%26+Company", "highestDiscount":"35.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Newegg", "id":"404", "url":"http://www.cardbear.com/gift-card-discount/404/Newegg", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"NFL Shop", "id":"325", "url":"http://www.cardbear.com/gift-card-discount/325/NFL+Shop", "highestDiscount":"13.48", "highestDiscountReseller":"cardcash"},
    {"storeName":"NHL Shop", "id":"290", "url":"http://www.cardbear.com/gift-card-discount/290/NHL+Shop", "highestDiscount":"12.00", "highestDiscountReseller":"raise"},
    {"storeName":"Nike", "id":"29", "url":"http://www.cardbear.com/gift-card-discount/29/Nike", "highestDiscount":"3.10", "highestDiscountReseller":"cardcash"},
    {"storeName":"Nine West", "id":"94", "url":"http://www.cardbear.com/gift-card-discount/94/Nine+West", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Ninety Nine", "id":"489", "url":"http://www.cardbear.com/gift-card-discount/489/Ninety+Nine", "highestDiscount":"12.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Noah's New York Bagels", "id":"485", "url":"http://www.cardbear.com/gift-card-discount/485/Noah%27s+New+York+Bagels", "highestDiscount":"20.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Nordstrom", "id":"25", "url":"http://www.cardbear.com/gift-card-discount/25/Nordstrom", "highestDiscount":"5.75", "highestDiscountReseller":"cardcash"},
    {"storeName":"Nordstrom Rack", "id":"371", "url":"http://www.cardbear.com/gift-card-discount/371/Nordstrom+Rack", "highestDiscount":"4.42", "highestDiscountReseller":"saveya"},
    {"storeName":"North Face", "id":"226", "url":"http://www.cardbear.com/gift-card-discount/226/North+Face", "highestDiscount":"12.50", "highestDiscountReseller":"cardcash"},
    {"storeName":"O'Charley's", "id":"480", "url":"http://www.cardbear.com/gift-card-discount/480/O%27Charley%27s", "highestDiscount":"10.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"O'Reilly", "id":"341", "url":"http://www.cardbear.com/gift-card-discount/341/O%27Reilly", "highestDiscount":"19.70", "highestDiscountReseller":"raise"},
    {"storeName":"Office Depot", "id":"84", "url":"http://www.cardbear.com/gift-card-discount/84/Office+Depot", "highestDiscount":"6.25", "highestDiscountReseller":"saveya"},
    {"storeName":"OfficeMax", "id":"112", "url":"http://www.cardbear.com/gift-card-discount/112/OfficeMax", "highestDiscount":"5.75", "highestDiscountReseller":"cardcash"},
    {"storeName":"Old Chicago", "id":"481", "url":"http://www.cardbear.com/gift-card-discount/481/Old+Chicago", "highestDiscount":"12.00", "highestDiscountReseller":"raise"},
    {"storeName":"Old Navy", "id":"83", "url":"http://www.cardbear.com/gift-card-discount/83/Old+Navy", "highestDiscount":"11.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Old Spaghetti Factory", "id":"269", "url":"http://www.cardbear.com/gift-card-discount/269/Old+Spaghetti+Factory", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Olive Garden", "id":"123", "url":"http://www.cardbear.com/gift-card-discount/123/Olive+Garden", "highestDiscount":"22.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Omaha Steaks", "id":"135", "url":"http://www.cardbear.com/gift-card-discount/135/Omaha+Steaks", "highestDiscount":"15.43", "highestDiscountReseller":"saveya"},
    {"storeName":"On the Border", "id":"196", "url":"http://www.cardbear.com/gift-card-discount/196/On+the+Border", "highestDiscount":"13.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Orchard Supply Hardware", "id":"282", "url":"http://www.cardbear.com/gift-card-discount/282/Orchard+Supply+Hardware", "highestDiscount":"19.79", "highestDiscountReseller":"cardcash"},
    {"storeName":"Original Penguin", "id":"329", "url":"http://www.cardbear.com/gift-card-discount/329/Original+Penguin", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Orvis", "id":"195", "url":"http://www.cardbear.com/gift-card-discount/195/Orvis", "highestDiscount":"18.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"OshKosh B'gosh", "id":"229", "url":"http://www.cardbear.com/gift-card-discount/229/OshKosh+B%27gosh", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Outback Steakhouse", "id":"53", "url":"http://www.cardbear.com/gift-card-discount/53/Outback+Steakhouse", "highestDiscount":"18.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Overstock", "id":"426", "url":"http://www.cardbear.com/gift-card-discount/426/Overstock", "highestDiscount":"5.70", "highestDiscountReseller":"raise"},
    {"storeName":"PacSun", "id":"126", "url":"http://www.cardbear.com/gift-card-discount/126/PacSun", "highestDiscount":"22.20", "highestDiscountReseller":"raise"},
    {"storeName":"Panda Express", "id":"129", "url":"http://www.cardbear.com/gift-card-discount/129/Panda+Express", "highestDiscount":"15.90", "highestDiscountReseller":"cardcash"},
    {"storeName":"Pandora", "id":"460", "url":"http://www.cardbear.com/gift-card-discount/460/Pandora", "highestDiscount":"6.00", "highestDiscountReseller":"raise"},
    {"storeName":"Panera Bread", "id":"105", "url":"http://www.cardbear.com/gift-card-discount/105/Panera+Bread", "highestDiscount":"20.75", "highestDiscountReseller":"cardcash"},
    {"storeName":"Papa John's Pizza", "id":"102", "url":"http://www.cardbear.com/gift-card-discount/102/Papa+John%27s+Pizza", "highestDiscount":"6.50", "highestDiscountReseller":"raise"},
    {"storeName":"Papa Murphy's", "id":"438", "url":"http://www.cardbear.com/gift-card-discount/438/Papa+Murphy%27s", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Paper Source", "id":"459", "url":"http://www.cardbear.com/gift-card-discount/459/Paper+Source", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Papyrus", "id":"423", "url":"http://www.cardbear.com/gift-card-discount/423/Papyrus", "highestDiscount":"30.00", "highestDiscountReseller":"raise"},
    {"storeName":"Patagonia", "id":"368", "url":"http://www.cardbear.com/gift-card-discount/368/Patagonia", "highestDiscount":"19.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"Payless Shoes", "id":"99", "url":"http://www.cardbear.com/gift-card-discount/99/Payless+Shoes", "highestDiscount":"10.00", "highestDiscountReseller":"raise"},
    {"storeName":"Pea In The Pod", "id":"35", "url":"http://www.cardbear.com/gift-card-discount/35/Pea+In+The+Pod", "highestDiscount":"10.10", "highestDiscountReseller":"raise"},
    {"storeName":"Peet's Coffee", "id":"260", "url":"http://www.cardbear.com/gift-card-discount/260/Peet%27s+Coffee", "highestDiscount":"17.82", "highestDiscountReseller":"cardcash"},
    {"storeName":"Pei Wei Asian Diner", "id":"437", "url":"http://www.cardbear.com/gift-card-discount/437/Pei+Wei+Asian+Diner", "highestDiscount":"17.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"Pep Boys", "id":"244", "url":"http://www.cardbear.com/gift-card-discount/244/Pep+Boys", "highestDiscount":"11.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Perry Ellis", "id":"134", "url":"http://www.cardbear.com/gift-card-discount/134/Perry+Ellis", "highestDiscount":"16.40", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Pet Food Express", "id":"364", "url":"http://www.cardbear.com/gift-card-discount/364/Pet+Food+Express", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Petco", "id":"13", "url":"http://www.cardbear.com/gift-card-discount/13/Petco", "highestDiscount":"25.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"PetSmart", "id":"109", "url":"http://www.cardbear.com/gift-card-discount/109/PetSmart", "highestDiscount":"17.74", "highestDiscountReseller":"saveya"},
    {"storeName":"PF Changs", "id":"183", "url":"http://www.cardbear.com/gift-card-discount/183/PF+Changs", "highestDiscount":"20.26", "highestDiscountReseller":"saveya"},
    {"storeName":"PGA Superstore", "id":"483", "url":"http://www.cardbear.com/gift-card-discount/483/PGA+Superstore", "highestDiscount":"13.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Phillips 66 Gas", "id":"507", "url":"http://www.cardbear.com/gift-card-discount/507/Phillips+66+Gas", "highestDiscount":"1.50", "highestDiscountReseller":"raise"},
    {"storeName":"Picture People", "id":"194", "url":"http://www.cardbear.com/gift-card-discount/194/Picture+People", "highestDiscount":"23.50", "highestDiscountReseller":"raise"},
    {"storeName":"Pier 1 Imports", "id":"125", "url":"http://www.cardbear.com/gift-card-discount/125/Pier+1+Imports", "highestDiscount":"18.10", "highestDiscountReseller":"cardcash"},
    {"storeName":"Pinkberry", "id":"232", "url":"http://www.cardbear.com/gift-card-discount/232/Pinkberry", "highestDiscount":"25.82", "highestDiscountReseller":"cardcash"},
    {"storeName":"Piperlime", "id":"292", "url":"http://www.cardbear.com/gift-card-discount/292/Piperlime", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Pizza Hut", "id":"22", "url":"http://www.cardbear.com/gift-card-discount/22/Pizza+Hut", "highestDiscount":"7.75", "highestDiscountReseller":"cardcash"},
    {"storeName":"Potbelly", "id":"238", "url":"http://www.cardbear.com/gift-card-discount/238/Potbelly", "highestDiscount":"18.40", "highestDiscountReseller":"cardcash"},
    {"storeName":"Pottery Barn", "id":"42", "url":"http://www.cardbear.com/gift-card-discount/42/Pottery+Barn", "highestDiscount":"7.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Pottery Barn Kids", "id":"405", "url":"http://www.cardbear.com/gift-card-discount/405/Pottery+Barn+Kids", "highestDiscount":"0.90", "highestDiscountReseller":"raise"},
    {"storeName":"Prada", "id":"296", "url":"http://www.cardbear.com/gift-card-discount/296/Prada", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Puma", "id":"193", "url":"http://www.cardbear.com/gift-card-discount/193/Puma", "highestDiscount":"11.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Qdoba", "id":"494", "url":"http://www.cardbear.com/gift-card-discount/494/Qdoba", "highestDiscount":"16.67", "highestDiscountReseller":"cardcash"},
    {"storeName":"Quiznos", "id":"214", "url":"http://www.cardbear.com/gift-card-discount/214/Quiznos", "highestDiscount":"10.00", "highestDiscountReseller":"raise"},
    {"storeName":"RadioShack", "id":"133", "url":"http://www.cardbear.com/gift-card-discount/133/RadioShack", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Ralph Lauren", "id":"414", "url":"http://www.cardbear.com/gift-card-discount/414/Ralph+Lauren", "highestDiscount":"3.50", "highestDiscountReseller":"cardcash"},
    {"storeName":"Ralphs", "id":"435", "url":"http://www.cardbear.com/gift-card-discount/435/Ralphs", "highestDiscount":"1.00", "highestDiscountReseller":"raise"},
    {"storeName":"Raymour & Flanigan", "id":"490", "url":"http://www.cardbear.com/gift-card-discount/490/Raymour+%26+Flanigan", "highestDiscount":"11.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Red Lobster", "id":"49", "url":"http://www.cardbear.com/gift-card-discount/49/Red+Lobster", "highestDiscount":"19.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Red Robin", "id":"248", "url":"http://www.cardbear.com/gift-card-discount/248/Red+Robin", "highestDiscount":"17.10", "highestDiscountReseller":"raise"},
    {"storeName":"Reebok", "id":"278", "url":"http://www.cardbear.com/gift-card-discount/278/Reebok", "highestDiscount":"12.50", "highestDiscountReseller":"cardcash"},
    {"storeName":"Regal Cinemas", "id":"41", "url":"http://www.cardbear.com/gift-card-discount/41/Regal+Cinemas", "highestDiscount":"15.50", "highestDiscountReseller":"cardcash"},
    {"storeName":"REI", "id":"186", "url":"http://www.cardbear.com/gift-card-discount/186/REI", "highestDiscount":"6.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Restaurant.com", "id":"283", "url":"http://www.cardbear.com/gift-card-discount/283/Restaurant.com", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Restoration Hardware", "id":"444", "url":"http://www.cardbear.com/gift-card-discount/444/Restoration+Hardware", "highestDiscount":"5.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Rite Aid", "id":"75", "url":"http://www.cardbear.com/gift-card-discount/75/Rite+Aid", "highestDiscount":"13.58", "highestDiscountReseller":"saveya"},
    {"storeName":"Ritz Carlton", "id":"396", "url":"http://www.cardbear.com/gift-card-discount/396/Ritz+Carlton", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Ross", "id":"40", "url":"http://www.cardbear.com/gift-card-discount/40/Ross", "highestDiscount":"11.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Roy's Hawaiian Fusion", "id":"395", "url":"http://www.cardbear.com/gift-card-discount/395/Roy%27s+Hawaiian+Fusion", "highestDiscount":"30.03", "highestDiscountReseller":"cardcash"},
    {"storeName":"Rubio's", "id":"412", "url":"http://www.cardbear.com/gift-card-discount/412/Rubio%27s", "highestDiscount":"15.00", "highestDiscountReseller":"raise"},
    {"storeName":"Ruby Tuesday", "id":"189", "url":"http://www.cardbear.com/gift-card-discount/189/Ruby+Tuesday", "highestDiscount":"17.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"rue21", "id":"190", "url":"http://www.cardbear.com/gift-card-discount/190/rue21", "highestDiscount":"24.00", "highestDiscountReseller":"raise"},
    {"storeName":"Ruth's Chris Steak House", "id":"313", "url":"http://www.cardbear.com/gift-card-discount/313/Ruth%27s+Chris+Steak+House", "highestDiscount":"12.05", "highestDiscountReseller":"saveya"},
    {"storeName":"Safeway", "id":"234", "url":"http://www.cardbear.com/gift-card-discount/234/Safeway", "highestDiscount":"0.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Saks Fifth Avenue", "id":"188", "url":"http://www.cardbear.com/gift-card-discount/188/Saks+Fifth+Avenue", "highestDiscount":"4.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Sally Beauty", "id":"448", "url":"http://www.cardbear.com/gift-card-discount/448/Sally+Beauty", "highestDiscount":"26.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Sam Ash", "id":"505", "url":"http://www.cardbear.com/gift-card-discount/505/Sam+Ash", "highestDiscount":"12.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Sears", "id":"143", "url":"http://www.cardbear.com/gift-card-discount/143/Sears", "highestDiscount":"6.00", "highestDiscountReseller":"raise"},
    {"storeName":"See's Candies", "id":"478", "url":"http://www.cardbear.com/gift-card-discount/478/See%27s+Candies", "highestDiscount":"28.30", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Sephora", "id":"72", "url":"http://www.cardbear.com/gift-card-discount/72/Sephora", "highestDiscount":"12.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Shake Shack", "id":"346", "url":"http://www.cardbear.com/gift-card-discount/346/Shake+Shack", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Shell", "id":"390", "url":"http://www.cardbear.com/gift-card-discount/390/Shell", "highestDiscount":"1.50", "highestDiscountReseller":"raise"},
    {"storeName":"Shoe Carnival", "id":"335", "url":"http://www.cardbear.com/gift-card-discount/335/Shoe+Carnival", "highestDiscount":"15.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Skechers", "id":"274", "url":"http://www.cardbear.com/gift-card-discount/274/Skechers", "highestDiscount":"5.10", "highestDiscountReseller":"raise"},
    {"storeName":"Smashburger", "id":"246", "url":"http://www.cardbear.com/gift-card-discount/246/Smashburger", "highestDiscount":"13.50", "highestDiscountReseller":"cardcash"},
    {"storeName":"Smith & Wollensky", "id":"492", "url":"http://www.cardbear.com/gift-card-discount/492/Smith+%26+Wollensky", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Smokey Bones", "id":"482", "url":"http://www.cardbear.com/gift-card-discount/482/Smokey+Bones", "highestDiscount":"19.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"Soma Intimates", "id":"477", "url":"http://www.cardbear.com/gift-card-discount/477/Soma+Intimates", "highestDiscount":"27.52", "highestDiscountReseller":"saveya"},
    {"storeName":"Sonic", "id":"326", "url":"http://www.cardbear.com/gift-card-discount/326/Sonic", "highestDiscount":"7.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Sony", "id":"297", "url":"http://www.cardbear.com/gift-card-discount/297/Sony", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Southwest Airlines", "id":"119", "url":"http://www.cardbear.com/gift-card-discount/119/Southwest+Airlines", "highestDiscount":"3.25", "highestDiscountReseller":"cardcash"},
    {"storeName":"Spa Week", "id":"312", "url":"http://www.cardbear.com/gift-card-discount/312/Spa+Week", "highestDiscount":"7.00", "highestDiscountReseller":"raise"},
    {"storeName":"Spa Wish", "id":"425", "url":"http://www.cardbear.com/gift-card-discount/425/Spa+Wish", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"SpaFinder", "id":"254", "url":"http://www.cardbear.com/gift-card-discount/254/SpaFinder", "highestDiscount":"10.75", "highestDiscountReseller":"cardcash"},
    {"storeName":"Speedway", "id":"503", "url":"http://www.cardbear.com/gift-card-discount/503/Speedway", "highestDiscount":"8.14", "highestDiscountReseller":"saveya"},
    {"storeName":"Spencer's", "id":"23", "url":"http://www.cardbear.com/gift-card-discount/23/Spencer%27s", "highestDiscount":"33.63", "highestDiscountReseller":"cardcash"},
    {"storeName":"Sports Authority", "id":"20", "url":"http://www.cardbear.com/gift-card-discount/20/Sports+Authority", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Sprouts Farmers Market", "id":"233", "url":"http://www.cardbear.com/gift-card-discount/233/Sprouts+Farmers+Market", "highestDiscount":"1.80", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Stage Bealls Peebles", "id":"475", "url":"http://www.cardbear.com/gift-card-discount/475/Stage+Bealls+Peebles", "highestDiscount":"26.51", "highestDiscountReseller":"saveya"},
    {"storeName":"Staples", "id":"85", "url":"http://www.cardbear.com/gift-card-discount/85/Staples", "highestDiscount":"5.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Starbucks", "id":"127", "url":"http://www.cardbear.com/gift-card-discount/127/Starbucks", "highestDiscount":"9.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Steak N Shake", "id":"50", "url":"http://www.cardbear.com/gift-card-discount/50/Steak+N+Shake", "highestDiscount":"25.26", "highestDiscountReseller":"cardcash"},
    {"storeName":"Stein Mart", "id":"187", "url":"http://www.cardbear.com/gift-card-discount/187/Stein+Mart", "highestDiscount":"28.00", "highestDiscountReseller":"raise"},
    {"storeName":"Steiner Sports", "id":"21", "url":"http://www.cardbear.com/gift-card-discount/21/Steiner+Sports", "highestDiscount":"15.00", "highestDiscountReseller":"raise"},
    {"storeName":"Steve Madden", "id":"265", "url":"http://www.cardbear.com/gift-card-discount/265/Steve+Madden", "highestDiscount":"22.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"Stride Rite", "id":"266", "url":"http://www.cardbear.com/gift-card-discount/266/Stride+Rite", "highestDiscount":"12.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Subway", "id":"73", "url":"http://www.cardbear.com/gift-card-discount/73/Subway", "highestDiscount":"10.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Sunglass Hut", "id":"276", "url":"http://www.cardbear.com/gift-card-discount/276/Sunglass+Hut", "highestDiscount":"23.10", "highestDiscountReseller":"cardcash"},
    {"storeName":"Sunoco", "id":"508", "url":"http://www.cardbear.com/gift-card-discount/508/Sunoco", "highestDiscount":"5.16", "highestDiscountReseller":"saveya"},
    {"storeName":"Supercuts", "id":"442", "url":"http://www.cardbear.com/gift-card-discount/442/Supercuts", "highestDiscount":"10.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Sur La Table", "id":"472", "url":"http://www.cardbear.com/gift-card-discount/472/Sur+La+Table", "highestDiscount":"11.20", "highestDiscountReseller":"raise"},
    {"storeName":"Swarovski", "id":"380", "url":"http://www.cardbear.com/gift-card-discount/380/Swarovski", "highestDiscount":"12.30", "highestDiscountReseller":"cardcash"},
    {"storeName":"Swatch", "id":"389", "url":"http://www.cardbear.com/gift-card-discount/389/Swatch", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Sweet Tomatoes Souplantation", "id":"216", "url":"http://www.cardbear.com/gift-card-discount/216/Sweet+Tomatoes+Souplantation", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Taco Bell", "id":"416", "url":"http://www.cardbear.com/gift-card-discount/416/Taco+Bell", "highestDiscount":"12.50", "highestDiscountReseller":"cardcash"},
    {"storeName":"Talbots", "id":"38", "url":"http://www.cardbear.com/gift-card-discount/38/Talbots", "highestDiscount":"33.15", "highestDiscountReseller":"cardcash"},
    {"storeName":"Target", "id":"31", "url":"http://www.cardbear.com/gift-card-discount/31/Target", "highestDiscount":"6.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Teavana", "id":"332", "url":"http://www.cardbear.com/gift-card-discount/332/Teavana", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Texas Roadhouse", "id":"56", "url":"http://www.cardbear.com/gift-card-discount/56/Texas+Roadhouse", "highestDiscount":"14.00", "highestDiscountReseller":"saveya"},
    {"storeName":"TGI Fridays", "id":"113", "url":"http://www.cardbear.com/gift-card-discount/113/TGI+Fridays", "highestDiscount":"25.79", "highestDiscountReseller":"cardcash"},
    {"storeName":"The Body Shop", "id":"387", "url":"http://www.cardbear.com/gift-card-discount/387/The+Body+Shop", "highestDiscount":"11.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"The Bouqs", "id":"361", "url":"http://www.cardbear.com/gift-card-discount/361/The+Bouqs", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"The Counter", "id":"463", "url":"http://www.cardbear.com/gift-card-discount/463/The+Counter", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Ticket VIP", "id":"342", "url":"http://www.cardbear.com/gift-card-discount/342/Ticket+VIP", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Ticketmaster", "id":"182", "url":"http://www.cardbear.com/gift-card-discount/182/Ticketmaster", "highestDiscount":"2.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Tiffany & Co", "id":"177", "url":"http://www.cardbear.com/gift-card-discount/177/Tiffany+%26+Co", "highestDiscount":"4.26", "highestDiscountReseller":"saveya"},
    {"storeName":"TigerDirect", "id":"47", "url":"http://www.cardbear.com/gift-card-discount/47/TigerDirect", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Tilly's", "id":"378", "url":"http://www.cardbear.com/gift-card-discount/378/Tilly%27s", "highestDiscount":"18.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Tim Hortons", "id":"333", "url":"http://www.cardbear.com/gift-card-discount/333/Tim+Hortons", "highestDiscount":"8.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Timberland", "id":"231", "url":"http://www.cardbear.com/gift-card-discount/231/Timberland", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"TJ Maxx", "id":"18", "url":"http://www.cardbear.com/gift-card-discount/18/TJ+Maxx", "highestDiscount":"16.41", "highestDiscountReseller":"saveya"},
    {"storeName":"Togo's", "id":"429", "url":"http://www.cardbear.com/gift-card-discount/429/Togo%27s", "highestDiscount":"12.00", "highestDiscountReseller":"raise"},
    {"storeName":"Tommy Bahama", "id":"381", "url":"http://www.cardbear.com/gift-card-discount/381/Tommy+Bahama", "highestDiscount":"25.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Tommy Hilfiger", "id":"388", "url":"http://www.cardbear.com/gift-card-discount/388/Tommy+Hilfiger", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Tony Roma's", "id":"486", "url":"http://www.cardbear.com/gift-card-discount/486/Tony+Roma%27s", "highestDiscount":"10.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Torrid", "id":"250", "url":"http://www.cardbear.com/gift-card-discount/250/Torrid", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Tory Burch", "id":"222", "url":"http://www.cardbear.com/gift-card-discount/222/Tory+Burch", "highestDiscount":"9.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Toys R Us", "id":"70", "url":"http://www.cardbear.com/gift-card-discount/70/Toys+R+Us", "highestDiscount":"7.80", "highestDiscountReseller":"raise"},
    {"storeName":"Tractor Supply Company", "id":"491", "url":"http://www.cardbear.com/gift-card-discount/491/Tractor+Supply+Company", "highestDiscount":"15.00", "highestDiscountReseller":"raise"},
    {"storeName":"Trader Joe's", "id":"212", "url":"http://www.cardbear.com/gift-card-discount/212/Trader+Joe%27s", "highestDiscount":"1.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Tropical Smoothie", "id":"284", "url":"http://www.cardbear.com/gift-card-discount/284/Tropical+Smoothie", "highestDiscount":"14.80", "highestDiscountReseller":"cardcash"},
    {"storeName":"True Religion", "id":"178", "url":"http://www.cardbear.com/gift-card-discount/178/True+Religion", "highestDiscount":"16.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Tumi", "id":"348", "url":"http://www.cardbear.com/gift-card-discount/348/Tumi", "highestDiscount":"13.00", "highestDiscountReseller":"raise"},
    {"storeName":"UGG Australia", "id":"408", "url":"http://www.cardbear.com/gift-card-discount/408/UGG+Australia", "highestDiscount":"32.84", "highestDiscountReseller":"saveya"},
    {"storeName":"Ulta", "id":"372", "url":"http://www.cardbear.com/gift-card-discount/372/Ulta", "highestDiscount":"9.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Under Armour", "id":"367", "url":"http://www.cardbear.com/gift-card-discount/367/Under+Armour", "highestDiscount":"12.68", "highestDiscountReseller":"saveya"},
    {"storeName":"Uniqlo", "id":"237", "url":"http://www.cardbear.com/gift-card-discount/237/Uniqlo", "highestDiscount":"8.00", "highestDiscountReseller":"raise"},
    {"storeName":"United Airlines", "id":"185", "url":"http://www.cardbear.com/gift-card-discount/185/United+Airlines", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"Uno Chicago Grill", "id":"179", "url":"http://www.cardbear.com/gift-card-discount/179/Uno+Chicago+Grill", "highestDiscount":"15.10", "highestDiscountReseller":"saveya"},
    {"storeName":"Urban Outfitters", "id":"285", "url":"http://www.cardbear.com/gift-card-discount/285/Urban+Outfitters", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"US Airways", "id":"219", "url":"http://www.cardbear.com/gift-card-discount/219/US+Airways", "highestDiscount":"0.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Vans", "id":"406", "url":"http://www.cardbear.com/gift-card-discount/406/Vans", "highestDiscount":"1.60", "highestDiscountReseller":"raise"},
    {"storeName":"Victoria's Secret", "id":"27", "url":"http://www.cardbear.com/gift-card-discount/27/Victoria%27s+Secret", "highestDiscount":"5.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Vitamin Shoppe", "id":"421", "url":"http://www.cardbear.com/gift-card-discount/421/Vitamin+Shoppe", "highestDiscount":"5.00", "highestDiscountReseller":"raise"},
    {"storeName":"Von Maur", "id":"498", "url":"http://www.cardbear.com/gift-card-discount/498/Von+Maur", "highestDiscount":"13.30", "highestDiscountReseller":"cardcash"},
    {"storeName":"Walgreens", "id":"76", "url":"http://www.cardbear.com/gift-card-discount/76/Walgreens", "highestDiscount":"14.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Walking Company", "id":"30", "url":"http://www.cardbear.com/gift-card-discount/30/Walking+Company", "highestDiscount":"15.10", "highestDiscountReseller":"raise"},
    {"storeName":"Walmart", "id":"4", "url":"http://www.cardbear.com/gift-card-discount/4/Walmart", "highestDiscount":"3.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Wendy's", "id":"52", "url":"http://www.cardbear.com/gift-card-discount/52/Wendy%27s", "highestDiscount":"0.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"West Elm", "id":"10", "url":"http://www.cardbear.com/gift-card-discount/10/West+Elm", "highestDiscount":"0.90", "highestDiscountReseller":"raise"},
    {"storeName":"West Marine", "id":"424", "url":"http://www.cardbear.com/gift-card-discount/424/West+Marine", "highestDiscount":"15.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Wet Seal", "id":"46", "url":"http://www.cardbear.com/gift-card-discount/46/Wet+Seal", "highestDiscount":"20.00", "highestDiscountReseller":"raise"},
    {"storeName":"Whataburger", "id":"228", "url":"http://www.cardbear.com/gift-card-discount/228/Whataburger", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"White Castle", "id":"268", "url":"http://www.cardbear.com/gift-card-discount/268/White+Castle", "highestDiscount":"0.00", "highestDiscountReseller":"raise"},
    {"storeName":"White House Black Market", "id":"509", "url":"http://www.cardbear.com/gift-card-discount/509/White+House+Black+Market", "highestDiscount":"24.60", "highestDiscountReseller":"cardcash"},
    {"storeName":"Whole Foods", "id":"104", "url":"http://www.cardbear.com/gift-card-discount/104/Whole+Foods", "highestDiscount":"2.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Williams Sonoma", "id":"45", "url":"http://www.cardbear.com/gift-card-discount/45/Williams+Sonoma", "highestDiscount":"8.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Wilson Leathers", "id":"91", "url":"http://www.cardbear.com/gift-card-discount/91/Wilson+Leathers", "highestDiscount":"27.20", "highestDiscountReseller":"cardcash"},
    {"storeName":"Wingstop", "id":"272", "url":"http://www.cardbear.com/gift-card-discount/272/Wingstop", "highestDiscount":"17.00", "highestDiscountReseller":"raise"},
    {"storeName":"Xbox Store", "id":"360", "url":"http://www.cardbear.com/gift-card-discount/360/Xbox+Store", "highestDiscount":"2.00", "highestDiscountReseller":"raise"},
    {"storeName":"Yankee Candle", "id":"9", "url":"http://www.cardbear.com/gift-card-discount/9/Yankee+Candle", "highestDiscount":"15.00", "highestDiscountReseller":"cardpool"},
    {"storeName":"Yard House", "id":"11", "url":"http://www.cardbear.com/gift-card-discount/11/Yard+House", "highestDiscount":"11.30", "highestDiscountReseller":"raise"},
    {"storeName":"Yogurtland", "id":"310", "url":"http://www.cardbear.com/gift-card-discount/310/Yogurtland", "highestDiscount":"23.80", "highestDiscountReseller":"raise"},
    {"storeName":"Z Gallerie", "id":"267", "url":"http://www.cardbear.com/gift-card-discount/267/Z+Gallerie", "highestDiscount":"12.00", "highestDiscountReseller":"saveya"},
    {"storeName":"Zales", "id":"8", "url":"http://www.cardbear.com/gift-card-discount/8/Zales", "highestDiscount":"18.80", "highestDiscountReseller":"raise"},
    {"storeName":"Zappos", "id":"218", "url":"http://www.cardbear.com/gift-card-discount/218/Zappos", "highestDiscount":"20.00", "highestDiscountReseller":"cardcash"},
    {"storeName":"Zara", "id":"471", "url":"http://www.cardbear.com/gift-card-discount/471/Zara", "highestDiscount":"3.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Zaxby's", "id":"363", "url":"http://www.cardbear.com/gift-card-discount/363/Zaxby%27s", "highestDiscount":"17.00", "highestDiscountReseller":"giftcardzen"},
    {"storeName":"Zumiez", "id":"303", "url":"http://www.cardbear.com/gift-card-discount/303/Zumiez", "highestDiscount":"11.30", "highestDiscountReseller":"cardcash"}
]}